app = "jlewis-sh-blog"
primary_region = "dfw"

swap_size_mb = 2_048

[build]
image = "johnandmaritza:latest"

[http_service]
auto_start_machines = false
auto_stop_machines = "stop"
internal_port = 3_000
min_machines_running = 0

[http_service.http_options]
h2_backend = true

[[vm]]
size = "shared-cpu-1x"
