
tab_spaces = 2
# hard_tabs = true
max_width = 80
group_imports = "StdExternalCrate"
reorder_imports = true
imports_granularity = "Crate"
format_strings = true
overflow_delimited_expr = true
struct_field_align_threshold = 20
wrap_comments = true
fn_single_line = true
